# ================================
# Configuração do MGT-Chat
# ================================

[general]
# Ativar logs de debug do chat
debug = false

# Formato do chat global
# Placeholders: {prefix} (LuckPerms), {player}, {message_color}, {message}
globalFormat = "&8[&3g&8] &r{prefix}&r{player}&f: {message_color}{message}"

# Formato do chat local
# Placeholders: {prefix} (LuckPerms), {player}, {message_color}, {message}
localFormat = "&8[&el&8] &r{prefix}&r{player}&f: {message_color}{message}"

# Cor aplicada às mensagens globais
globalMessageColor = "&3"

# Cor aplicada às mensagens locais
localMessageColor = "&e"

# Distância máxima (em blocos) para o chat local
localRange = 100

# Permitir uso de cores hexadecimais no chat (ex: &#FFAA00)
allowHexColors = true

# Permitir uso de códigos de cor & e §
allowLegacyColors = true

[antiSpam]
# Tempo mínimo entre mensagens (em milissegundos)
messageDelay = 2000

# Bloquear mensagens repetidas consecutivas
blockRepeated = true

# Número máximo de mensagens iguais permitidas em sequência
maxRepeated = 2

[filter]
# Ativar filtro de palavras proibidas
enabled = true

# Lista de palavras bloqueadas (case-insensitive)
blockedWords = [
    "palavrão1",
    "palavrão2",
    "palavrão3"
]

# Mensagem substituta quando palavra bloqueada for detectada
replacement = "***"


[private]
# Placeholders: {send_player}, {receive_player}, {message}
tellFormatTo = "&8[&cr&8] &7Sussurrou para &r{receive_player}: &c{message}"
tellFormatFrom = "&8[&cr&8] &r{send_player} &7sussurrou: &c{message}"
replyTellFormatTo = "&8[&cr&8] &7Sussurou para &r{receive_player}: &c{message}"
replyTellFormatFrom = "&8[&cr&8] &r{send_player} &7sussurrou: &c{message}"

