modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="mgtchat"
version="1.0.0-SNAPSHOT"
displayName="MGT-Chat"
authors="GnomoMuitoLoco"
description='''Esse mod é uma dependência para outros mods MGT e nada mais.'''

[[dependencies.mgtchat]]
modId="neoforge"
type="required"
versionRange="[21.1.211,)"
ordering="NONE"
side="BOTH"

[[dependencies.mgtchat]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"

[[dependencies.mgtchat]]
modId="mgtcore"
type="required"
versionRange="[1.0.1-SNAPSHOT,)"
ordering="AFTER"
side="BOTH"