name: Notificar Discord

on:
  push:
  create:
  pull_request:
    types: [opened, closed]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar notificação para o Discord
        run: |
          echo "Enviando notificação para o Discord..."
          curl -X POST -H "Content-Type: application/json" \
          -d '{
            "embeds": [{
              "title": "📢 Atualização no repositório",
              "description": "Evento: ${{ github.event_name }}\nAutor: ${{ github.actor }}\nRepositório: ${{ github.repository }}\nBranch: ${{ github.ref }}",
              "color": 5814783,
              "timestamp": "'$(date -u +%Y-%m-%dT%H:%M:%SZ)'"
            }]
          }' ${{ secrets.DISCORD_WEBHOOK }}
