name: Notificar Discord com commits

on:
  push:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar commits para o Discord
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          BRANCH_URL="https://github.com/${GITHUB_REPOSITORY}/tree/${BRANCH_NAME}"
          COUNT=$(jq '.commits | length' "$GITHUB_EVENT_PATH")
          AUTHOR="${GITHUB_ACTOR}"
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

          # Lista de commits (hash curto, link, mensagem e autor)
          COMMITS=$(jq -r \
            '.commits[] | "[`\(.id[0:7])`](\(.url)) \"\(.message)\" - \(.author.name)"'
            "$GITHUB_EVENT_PATH" | sed ':a;N;$!ba;s/\n/\\n/g')

          # Envia para o Discord
          curl -X POST -H "Content-Type: application/json" \
          -d "{
            \"username\": \"GitHub Bot\",
            \"avatar_url\": \"https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png\",
            \"embeds\": [{
              \"title\": \"📢 Atualização no repositório\",
              \"description\": \"🧑‍💻 Autor: ${AUTHOR}\\n📦 Repositório: ${GITHUB_REPOSITORY}\\n🌿 Branch: [${BRANCH_NAME}](${BRANCH_URL})\\n📌 ${COUNT} novo(s) commit(s):\\n${COMMITS}\",
              \"color\": 7506394,
              \"timestamp\": \"${TIMESTAMP}\"
            }]
          }" ${{ secrets.DISCORD_WEBHOOK }}
